In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
# Q1 Pandas Version
pd.__version__

'3.0.6'

In [6]:
# Q2 Records Count
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [7]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [8]:
len(df)

10000

In [9]:
# Q3 Fuel types
fuel_type_list=df['fuel_type'].unique()
print("Number of fuel types are : ", len(fuel_type_list))

Number of fuel types are :  3

In [10]:
# Q4 Missing Values
missing_cols=df.isna().sum()
num_missing_cols=(missing_cols>0).sum()
print("Number of missing columns are : ", num_missing_cols)

Number of missing columns are :  2

In [11]:
# Q5 Max fuel efficiency
fuel_efficiency_of_asian_cars=df[df['origin']=='Asia'].fuel_efficiency_mpg
print("Maximum fuel efficiency within asian cars is : ",max(fuel_efficiency_of_asian_cars))

Maximum fuel efficiency within asian cars is :  41.2

In [12]:
# Q6 Median Value of horsepower
horsepower_median=df['horsepower'].median()
print("horsepower median before filling : ", horsepower_median)

most_freq_horsepower=df['horsepower'].mode()[0]
df['horsepower'].fillna(most_freq_horsepower)
print("Missing values of horsepower are filled with most frequent value which is : ", most_freq_horsepower)

horsepower_median_new=df['horsepower'].median()
print("horsepower median after filling : ", horsepower_median_new)

horsepower median before filling :  254.0
Missing values of horsepower are filled with most frequent value which is :  252.0
horsepower median after filling :  254.0

In [13]:
# Q7 Sum of weights

asian_cars=df[df['origin']=='Asia'][['vehicle_weight','model_year']].head(7)
asian_cars

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [14]:
X=np.array(asian_cars)
XTX=np.dot(X.T, X)
inverse_XTX=np.linalg.inv(XTX)
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w=inverse_XTX.dot(X.T).dot(y)

print("Sum of all the elements of the result w : ", np.sum(w))

Sum of all the elements of the result w :  0.36919696904925486